version: '3'
services:

  web-app:
    image: node:18.0.0
    container_name: rest_front
    command: [sh, -c, "yarn && yarn dev"]
    ports:
      - "3001:3000"
    working_dir: '/webapp'
    tty: true
    volumes:
      - './:/webapp/'
    environment:
      HOST: 0.0.0.0
      PORT: 3000